config/routes.rb
Rails.application.routes.draw do
  resources :decks do
    resources :cards do
      put :change_status, on: :member
    end
    get :review, on: :member
  end

  root to: 'decks#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
  mount_uploader :image, ImageUploader
  scope :to_review, -> { where(status: 'active') }

  validates :front, :back, :image, presence: true
  enum status: { active: 0, inactive: 1 }
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards, dependent: :destroy
  belongs_to :user

  validates :title, :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :decks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  

  def user_not_authorized
    flash[:error] = 'You are not authorized to perform this action.'
    redirect_to(request.referrer, status: 301 || root_path, status: 301)
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_deck

  before_action :set_card, only: %i[show edit update destroy change_status]

  # GET decks/1/cards
  def index
    @cards = @deck.cards
  end

  # GET decks/1/cards/1
  def show; end

  # GET decks/1/cards/new
  def new
    @card = @deck.cards.build
  end

  # GET decks/1/cards/1/edit
  def edit; end

  # POST decks/1/cards
  def create
    @card = @deck.cards.build(card_params)

    if @card.save
      redirect_to(deck_url(@deck), notice: 'Card was successfully created.')
    else
      render action: 'new'
    end
  end

  # PUT decks/1/cards/1
  def update
    if @card.update_attributes(card_params)
      redirect_to(deck_url(@deck), notice: 'Card was successfully updated.')
    else
      render action: 'edit'
    end
  end

  # DELETE decks/1/cards/1
  def destroy
    @card.destroy

    redirect_to deck_url(@deck)
  end

  def change_status
    card = Card.find(params[:id])
    card.inactive!
    ChangeStatusWorker.perform_in(params[:time].to_i.minutes, card.id)
    redirect_to review_deck_path(@deck)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deck
    @deck = Deck.find(params[:deck_id])
  end

  def set_card
    @card = @deck.cards.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def card_params
    params.require(:card).permit(:front, :back, :status, :deck_id, :image)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: %i[show edit update destroy review]

  # GET /decks
  # GET /decks.json
  def index
    @decks = current_user.decks
  end

  # GET /decks/1
  # GET /decks/1.json
  def show; end

  # GET /decks/new
  def new
    @deck = current_user.decks.build
  end

  # GET /decks/1/edit
  def edit; end

  # POST /decks
  # POST /decks.json
  def create
    @deck = current_user.decks.build(deck_params)
    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { redirect_to decks_url, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { redirect_to decks_url, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def review
    @cards = @deck.cards.to_review
    if @cards.length.zero?
      flash[:alert] = 'Nothing to review'
      redirect_to decks_path
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deck
    @deck = Deck.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deck_params
    params.require(:deck).permit(:title, :description, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/_form.html.erb
<%= form_for([@card.deck, @card]) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h6>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :front %><br />
    <%= f.text_field :front %>
  </div>
  <div class="field">
    <%= f.label :back %><br />
    <%= f.text_field :back %>
  </div>
  <div>
    <%= f.label :image %><br />
    <%= f.file_field :image %>
  </div>
  <br />
  <div class="actions">
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
  </div>
  <br />
<% end %>

app/views/cards/edit.html.erb
<h5>Editing card</h5>

<%= render 'form' %>

<%= link_to 'Back', deck_path(@card.deck) %>

app/views/cards/index.html.erb
<h4 class='center'><%=@deck.title%> cards</h4>
<div class="row">
  <% @cards.each do |card| %>
    <div class="col s3">
      <div class="card sticky-action">
        <div class="card-image waves-effect waves-block waves-light">
          <div class="activator"><%= image_tag(card.image.url, alt: 'Image',:width => 200, :height => 200) if card.image? %></div>
        </div>
        <div class="card-content">
          <span class="card-title activator grey-text text-darken-4"><%= card.front %><i class="material-icons right">more_vert</i></span>
        </div>
        <div class="card-action">
          <%= link_to 'Edit', edit_deck_card_path(card.deck, card) %>
          <%= link_to 'Delete', [card.deck, card], method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
        <div class="card-reveal">
          <span class="card-title grey-text text-darken-4"><%= card.back %><i class="material-icons right">close</i></span>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br />
<div class="card-action">
  <%= link_to 'New Card', new_deck_card_path(params[:deck_id]) %>
</div>

app/views/cards/new.html.erb
<h5>New card</h5>

<%= render 'form' %>

<%= link_to 'Back', deck_path(@card.deck) %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Front:</b>
  <%= @card.front %>
  <p> <%= image_tag(@card.image.url, alt: 'Image',:width => 200, :height => 200) if @card.image? %></p>
</p>

<p>
  <b>Back:</b>
  <%= @card.back %>
</p>

<div>
<%= link_to 'Edit', edit_deck_card_path(@card.deck, @card) %> |
<%= link_to 'Back', deck_cards_path(@card.deck) %>
</div>

app/views/decks/_form.html.erb
<%= form_for(deck) do |f| %>
  <% if deck.errors.any? %>
    <div id="error_explanation">
      <h6><%= pluralize(deck.errors.count, "error") %> prohibited this deck from being saved:</h6>
      <ul>
        <% deck.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <br />
  <div class="actions">
    <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
  </div>
  <br />
<% end %>

app/views/decks/edit.html.erb
<h5>Editing Deck</h5>

<%= render 'form', deck: @deck %>

<%= link_to 'Back', deck_path(@deck) %>

app/views/decks/index.html.erb
<h4>Decks</h4>
<% if @decks.any?%>
  <table class="striped centered">
    <thead>
      <tr>
        <th>Title</th>
        <th>Description</th>
        <th>Cards</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @decks.each do |deck| %>
        <tr>
          <td><%= link_to deck.title, deck_path(deck)%></td>
          <td><%= deck.description %></td>
          <td><%= deck.cards.count%></td>
          <td>
            <a class="btn dropdown-trigger" href="#!" data-target="dropdown2">Dropdown<i class="material-icons right">arrow_drop_down</i></a>
          </td>
          <ul id="dropdown2" class="dropdown-content">
            <li><%= link_to 'Review', review_deck_path(deck) %></li>
            <li><%= link_to 'Show', deck_path(deck) %></li>
            <li><%= link_to 'Edit', edit_deck_path(deck) %></li>
            <li><%= link_to 'Delete', deck, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
<br>
<div class="card-action">
  <%= link_to 'New Deck', new_deck_path %>
</div>

app/views/decks/new.html.erb
<h5>New Deck</h5>

<%= render 'form', deck: @deck %>

<%= link_to 'Back', decks_path %>

app/views/decks/publicly_available.html.erb
<p id="notice"><%= notice %></p>

<h1>Decks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Cards</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%=deck.title%></td>
        <td><%= deck.description %></td>
        <td><%= deck.cards.count%></td>
        <td><%= link_to 'Review', review_deck_path(deck) %></td>
        <td><%= link_to 'Cards List', deck_cards_path(deck) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/decks/review.html.erb
<div class="row">
  <div class="carousel carousel-slider">
    <% @cards.each do |card| %>
      <a class="carousel-item" >
        <div class="col s12 center">
          <div class="col l4"></div>
          <div class='col l4'>
            <div class="card sticky-action">
              <div class="card-image waves-effect waves-block waves-light">
                <div class="activator"><%= image_tag(card.image.url, alt: 'Image',:width => 200, :height => 300) if card.image? %></div>
              </div>
              <div class="card-content">
                <span class="card-title activator grey-text text-darken-4"><%= card.front %><i class="material-icons right">more_vert</i></span>
              </div>
              <div class="card-reveal">
                <span class="card-title grey-text text-darken-4"><%= card.back %><i class="material-icons right">close</i></span>
                <div class="card-action">
                  <%= form_for(card, url: change_status_deck_card_path(card, deck_id: card.deck.id), method: :put) do |f| %>
                    <div class="col s12">
                      <%= f.button 'Wrong 1 min', name: 'time', value: 1, class: 'btn waves-effect waves-light btn-block red' %>
                    </div>
                    <div class="col s12">
                      <%= f.button 'Good 10 min', name: 'time', value: 10, class: 'btn waves-effect waves-light btn-block green' %>
                    </div>
                    <div class="col s12">
                      <%= f.button 'Exelent 30 min', name: 'time', value: 30, class: 'btn waves-effect waves-light btn-block blue' %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="col l4"></div>
        </div>
      </a>
    <% end %>
  </div>
</div>

app/views/decks/show.html.erb
<div class="section">
  <h5>
    <strong>Title:</strong>
    <%= @deck.title %>
  </h5>
  <h5>
    <strong>Description:</strong>
    <%= @deck.description %>
  </h5>
</div>
<div class="card-action">
  <%= link_to 'Create Card', new_deck_card_path(@deck) %>
  <%= link_to 'Review Cards', review_deck_path(@deck) %></li>
  <%= link_to 'Edit', edit_deck_path(@deck) %>
  <%= link_to 'Delete', @deck, method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Back', decks_path %>
</div>
<div class="divider"></div>
<% if @deck.cards.any?%>
  <h5><strong>Cards:</strong></h5>
  <div class="row">
    <% @deck.cards.each do |card| %>
      <div class="col m3">
        <div class="card sticky-action">
          <div class="card-image waves-effect waves-block waves-light">
            <div class="activator"><%= image_tag(card.image.url, alt: 'Image',:width => 200, :height => 200) if card.image? %></div>
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4"><%= card.front %><i class="material-icons right">more_vert</i></span>
          </div>
          <div class="card-action">
            <%= link_to 'Edit', edit_deck_card_path(card.deck, card) %>
            <%= link_to 'Delete', [card.deck, card], method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
          <div class="card-reveal">
            <span class="card-title grey-text text-darken-4"><%= card.back %><i class="material-icons right">close</i></span>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memorize</title>
    <%= csrf_meta_tags %>
  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body class='teal lighten-4'>
    <%= render 'shared/navbar' %>
    <%= render 'shared/messages'%>
    <div class="container">
      <div class="row">
        <div class="col s12">
          <div class="card ">
            <div class="card-panel">
              <div class="card-content ">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/shared/_messages.html.erb
<div class='messages center'>
    <p class="notice green-text"><%= notice %></p>
    <p class="alert red-text"><%= alert %></p>
</div>

app/views/shared/_navbar.html.erb
<nav>
  <div class="nav-wrapper  teal darken-2">
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to 'Decks', decks_path%></li>
      <% if user_signed_in? %>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>